// This file is generated automatically by scripts/generate-blog-data.mjs
// Do not edit this file manually.

import type { BlogPostProps } from '../interfaces/blogPost.ts';

export const generatedBlogPosts: BlogPostProps[] = [
  {
    "id": "my-first-post.md",
    "title": "My First Blog Post",
    "date": "19 abril 2025",
    "author": "Mateo",
    "slug": "my-first-post",
    "excerpt": "This is a short summary of my first blog post.",
    "categories": [
      "React",
      "TypeScript",
      "Web Development"
    ],
    "image": "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "content": "\n## Introduction\n\nThis is the main content of my **first blog post** written in Markdown!\n\nYou can include:\n\n- Lists\n- `Code snippets`\n- And more...\n"
  },
  {
    "id": "second-post.md",
    "title": "My Second Blog Post",
    "date": "20 abril 2025",
    "author": "Mateo",
    "slug": "my-second-post",
    "excerpt": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    "categories": [
      "Vue",
      "React"
    ],
    "image": "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "content": "\n## Introduction\n\nThis is the main content of my **first blog post** written in Markdown!\n\nYou can include:\n\n- Lists\n- `Code snippets`\n- And more...\n"
  }
];
